# Extended from errordeveloper/oracle-jre
FROM iron/scala

# Use the S6 init system -- personal preference I like it better than OpenRC
ADD https://github.com/just-containers/s6-overlay/releases/download/v1.11.0.1/s6-overlay-amd64.tar.gz /tmp/
RUN gunzip -c /tmp/s6-overlay-amd64.tar.gz | tar -xf - -C /

# Add files.
ADD portster /usr/local/bin/
ADD containerId.sh /usr/local/bin/
ADD run /etc/services.d/portster/run
RUN echo "#!/bin/sh" > /etc/services.d/portster/finish

CMD [ "/init" ]
